version: '3.0'

services:
  bot:
    build: .
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    command: python3 app.py

  db:
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - .:/app
    ports:
      - 5432:5432
    environment:
      DATABASE_NAME: ${NAME}
      DATABASE_USER: ${USER}
      DATABASE_PASSWORD: ${PASSWORD}
      DATABASE_HOST: ${HOST}
      DATABASE_PORT: 5432
volumes:
  postgres_data: